# Generated by Django 3.2.4 on 2021-06-25 09:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210625_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 9, 13, 53, 45783, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
