# Generated by Django 3.2.4 on 2021-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210625_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default='timezone.now()', verbose_name='Дата публикации'),
        ),
    ]
