# Generated by Django 3.2.4 on 2021-06-25 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 6, 54, 50, 185059, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
